[build]
  command = "yarn install && yarn build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "20"
  CI = "true"

[build.processing]
  skip_processing = false

[secrets_scan]
  enabled = false
